### ISSUE TITLE
Allow indexing by arbitrary RDF type

### ISSUE THREAD

**Issue by scossu** [fcrepo4-exts/fcrepo-camel-toolbox#67]
According to the documentation, currently the indexer can either be configured to act on resources of RDF type `indexing:Indexable` or on all resources (by setting the `indexing.predicate` property). 

This ticket is to introduce a configuration option that allows to specify which RDF type resources must be indexed. This avoids to explicitly add the `indexing:Indexable` type to every single resource that needs to be indexed. 

Ideally this property should be multi-valued, and set to `fedora:Resource` by default.

**Comment by ajs6f** [comment]
I'm not sure about `fedora:Resource` as a default type. Doesn't that include bitstreams?

**Comment by awoods** [comment]
Agreed, @ajs6f, `fedora:Resource` is probably not an ideal default. This ticket would boil down to making the following statement configurable:
https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/blob/master/fcrepo-indexing-triplestore/src/main/java/org/fcrepo/camel/indexing/triplestore/TriplestoreRouter.java#L54

Would it be alright to leave the default as is? `indexing:Indexable`?

**Comment by ajs6f** [comment]
Is there a type for "RDF-y" resources?

**Comment by awoods** [comment]
`http://www.w3.org/ns/ldp#RDFSource`

**Comment by ajs6f** [comment]
So maybe that's the default.

**Comment by awoods** [comment]
Currently there is a flag that indicates whether any RDF type filter should be employed or not:
https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/blob/master/fcrepo-indexing-triplestore/src/main/cfg/org.fcrepo.camel.indexing.triplestore.cfg#L14

If that flag is `false` (the default) all RDF sources are indexed. Making a new default be `ldp:RDFSource` would not add any value. The default should be more exclusive.

**Comment by ajs6f** [comment]
That oughtn't be a simple flag-and-RDF-type(s). It ought to be pluggable via (Java) type.

**Comment by awoods** [comment]
@acoburn, thoughts?

**Comment by acoburn** [comment]
@awoods it makes sense to me that the RDF-type should be pluggable. I'm not sure what @ajs6f has in mind with Java types, given that this needs to be definable in a text-based configuration file.

**Comment by ajs6f** [comment]
I'm saying the text-based configuration file will ultimately be insufficient, but I have no problem waiting until events demonstrate the fact.

**Comment by scossu** [comment]
Re. default: I proposed fedora:Resource because it seems to be closest to the current default. RDFSource includes pairtrees which I don't think makes much sense to index. 

Also, the current default (indexing:Indexable) requires additional action from the client that has to add that exstra property. That is what I am trying to avoid. 

What is the downside to including bitstreams? Would they be ignored because they are not RDF or would the indexer download them while it scans the resources?

**Comment by scossu** [comment]
> "closest to the current default" 

read: with the type filter off. I don't see pairtrees indexed in my triplestore currently.

**Comment by ajs6f** [comment]
Is this still relevant?

**Comment by scossu** [comment]
I will defer to @kefo for more details but I believe that we implemented something internally along the same lines.

**Comment by acoburn** [comment]
Closing as this is best handled by an external application-specific filter.
