### ISSUE TITLE
'created' field value is being converted to epoch from Date Format.

### ISSUE THREAD

**Issue by g1patnaik** [fcrepo4-exts/fcrepo-camel-toolbox#82]
Hi,

'created' and 'lastModified' field values or probably, all date values are being converted to epoch.

I am trying to index in solr 5.5. But the date values are coming in epoch format. Probably a bug.

**Comment by acoburn** [comment]
This is outside the scope of the camel toolkit.

Three recommendations:
1. Use a custom LDPath program as described here: https://wiki.duraspace.org/display/FEDORA4x/Indexing+Transformations
2. Verify your RDF properties are being converted properly to the correct format (see link above)
3. Verify that your Solr schema.xml is supporting the correct date types.

**Comment by awoods** [comment]
Additionally, a ticket was recently worked that ensures that dates coming out of the /fcr:transform service are not millis since the epoch, but formatted as date/times. This update will be available in the 4.5.1 release:
https://jira.duraspace.org/browse/FCREPO-1877
