### ISSUE TITLE
handling resource updates in indexing-triplestore

### ISSUE THREAD

**Issue by zozlak** [fcrepo4-exts/fcrepo-camel-toolbox#98]
Lets assume I have a binary resource with URI `X` in my Fedora repository.
Thanks to the indexing-triplestore plugin in my triplestore I can see triples like:
`<X> <http://www.loc.gov/premis/rdf/v1#hasSize> 10256`
`<X> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasMimeType> "text/xml"`
etc.

Unfortunately when I update the resource (overwrite it with a new content by issuing a PUT request to the Fedora repository) my triplestore looks like this:
`<X> <http://www.loc.gov/premis/rdf/v1#hasSize> 10256`
`<X> <http://www.loc.gov/premis/rdf/v1#hasSize> 8320`
`<X> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasMimeType> "text/xml"`
`<X> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasMimeType> "application/json"`
so I can see triples denoting both original and up to date state of the resource but I am unable to distinguish which one denotes the current state as all of them share the same subject <X>.

I think the old triples should be simply deleted.
While I know I can directly ask Fedora to reindex a given resource after I updated it but it seems to me quite inconvenient and it will be nice if the indexing plugin can handle it automatically.

There is also no support for versioning provided by the Fedora. When I create the snapshot (version) of a resource in the Fedora corresponding triples (with a `<X/fcr:versions/{versionName}>` subject) are not created and when I update the resource I run into the same problem as described above.

**Comment by acoburn** [comment]
@zozlak I would recommend reviewing this thread: https://groups.google.com/forum/#!msg/fedora-tech/raaOv3syx1E/P7Xjnw8jDgAJ

And no, there is no support for versioning, nor is that on the roadmap for the triplestore indexer.

**Comment by zozlak** [comment]
If I remember correctly this thread is about other use case. In the thread they were manually editing their own metadata with the PATCH query and I am talking about "technical Fedora metadata" (meaning ones automatically created by Fedora and not provided by the user) created by the Fedora on a PUT request to a binary resource. From your side it might not make a difference (metadata like any other) but from mine it does (as these are metadata which were not provided by me, why I should be responsible for manually removing their old values?).

**Comment by acoburn** [comment]
My point here is that your system is incorrectly configured. A correctly configured system will not encounter those duplicate triples, regardless of whether the triples refer to a container or a binary, and regardless of whether you are modifying that resource with a PUT, PATCH or POST.

The key issue is this: what is the `Host` header sent to the repository for the HTTP operation? And does that `Host` header value match the `Host` header used by the camel toolbox indexer. If those values don't match, you will end up with duplicate triples.

IMO, a well designed deployment will make Fedora accessible on port 80 or 443 over a proxy with a _single_ statically-defined Host header. This way, _all_ clients connect to Fedora with the same Host value and you don't ever encounter this sort of error.

If you're using nginx, this is the sort of configuration I use:

        location /fcrepo {
            proxy_pass http://localhost:8080;
            proxy_http_version 1.1;
            proxy_set_header Host repository.myinstitution.edu;
        }

This way, there is no ambiguity about the Host header sent to Fedora (and consequently, the hostname of the triples returned). That will solve the issue you describe.

**Comment by ajs6f** [comment]
This makes sense; perhaps we can add something to the README along the lines of your warning/advice?

**Comment by ajs6f** [comment]
Rocktacular, @acoburn !

**Comment by zozlak** [comment]
Sorry,
I was already aware that the `fcrepo.baseUrl` indexer configuration parameter must be in line with the Fedora host name clients are using. I have just missed then it also means I can not use `127.0.0.1` and `localhost` interchangeably when trying things out in my local testing environment.

**Comment by acoburn** [comment]
@zozlak That is correct. It is also true that you cannot exchange `CNAME`, `ALIAS` or `A` records or regular IP addresses (even if they all resolve to the same location) and expect they will mean the same thing to downstream applications.
